import type { ActivityItem, ChartPoint, ContentItem, PipelineRunRecord, PipelineTimelineRun } from "../types";

export const mockStats = {
  totalArticles: 47,
  published: 31,
  avgSeoScore: 8.4,
  thisWeek: 6,
};

const body = `## Executive Summary

Autonomous content systems combine research, drafting, editing, and scheduling into a repeatable publishing workflow. The highest-performing teams use these systems to increase topic coverage while keeping quality gates visible.

## Key Takeaways

- Multi-agent workflows reduce manual coordination by separating research, writing, review, and publishing tasks.
- Editorial quality improves when scoring and retry loops are explicit.
- Scheduling content through a task queue makes the publishing workflow observable and recoverable.

## Outlook

The next stage for AI content operations is not just faster drafting. It is reliable orchestration, traceability, and human-grade review surfaces that make automated work easy to inspect.`;

export const mockContent: ContentItem[] = [
  {
    id: "mock-1",
    topic: "Renewable Energy",
    title: "The Future of Solar Power: How Perovskite Cells Are Changing Everything",
    excerpt: "Scientists have achieved record efficiency with tandem perovskite-silicon solar cells.",
    body,
    wordCount: 1124,
    readTime: "5 min",
    seoScore: 9.1,
    readabilityScore: 8.7,
    engagementScore: 8.9,
    status: "published",
    publishedAt: "2026-05-12T09:00:00Z",
    scheduledAt: null,
    createdAt: "2026-05-12T08:00:00Z",
    tags: ["solar", "energy", "technology"],
    metaDescription: "A practical look at next-generation solar technology and market impact.",
  },
  {
    id: "mock-2",
    topic: "AI Operations",
    title: "Why Agentic Workflows Are Becoming the New Enterprise Automation Layer",
    excerpt: "AI agents are shifting from single prompts to production workflows with auditable outcomes.",
    body,
    wordCount: 980,
    readTime: "4 min",
    seoScore: 8.8,
    readabilityScore: 8.4,
    engagementScore: 9.0,
    status: "scheduled",
    publishedAt: null,
    scheduledAt: "2026-05-15T11:00:00Z",
    createdAt: "2026-05-14T11:00:00Z",
    tags: ["agents", "automation", "enterprise"],
    metaDescription: "How multi-agent AI systems are reshaping operational automation.",
  },
  {
    id: "mock-3",
    topic: "Climate Tech",
    title: "Carbon Capture Enters Its Infrastructure Era",
    excerpt: "Carbon capture is moving from pilot projects into infrastructure-grade deployments.",
    body,
    wordCount: 1240,
    readTime: "6 min",
    seoScore: 7.9,
    readabilityScore: 8.2,
    engagementScore: 8.1,
    status: "published",
    publishedAt: "2026-05-10T15:30:00Z",
    scheduledAt: null,
    createdAt: "2026-05-10T12:00:00Z",
    tags: ["carbon", "climate", "infrastructure"],
    metaDescription: "A review of carbon capture markets, economics, and deployment risks.",
  },
  {
    id: "mock-4",
    topic: "Cybersecurity",
    title: "Small Business Cybersecurity Trends That Will Matter This Year",
    excerpt: "Attackers are targeting smaller teams with sophisticated but preventable campaigns.",
    body,
    wordCount: 870,
    readTime: "4 min",
    seoScore: 8.2,
    readabilityScore: 8.6,
    engagementScore: 7.8,
    status: "published",
    publishedAt: "2026-05-09T10:00:00Z",
    scheduledAt: null,
    createdAt: "2026-05-09T08:30:00Z",
    tags: ["security", "smb", "risk"],
    metaDescription: "The cybersecurity priorities small businesses should understand now.",
  },
  {
    id: "mock-5",
    topic: "Healthcare AI",
    title: "Clinical AI Assistants and the New Standard for Patient Documentation",
    excerpt: "Healthcare teams are adopting AI assistants to reduce documentation overhead.",
    body,
    wordCount: 1160,
    readTime: "5 min",
    seoScore: 8.5,
    readabilityScore: 8.8,
    engagementScore: 8.0,
    status: "scheduled",
    publishedAt: null,
    scheduledAt: "2026-05-16T13:00:00Z",
    createdAt: "2026-05-13T13:20:00Z",
    tags: ["healthcare", "ai", "workflow"],
    metaDescription: "How AI documentation tools are changing clinical operations.",
  },
  {
    id: "mock-6",
    topic: "Fintech",
    title: "Real-Time Payments Are Redefining Customer Expectations",
    excerpt: "Faster payments are becoming table stakes for modern financial products.",
    body,
    wordCount: 760,
    readTime: "3 min",
    seoScore: 7.6,
    readabilityScore: 8.0,
    engagementScore: 7.7,
    status: "published",
    publishedAt: "2026-05-08T09:45:00Z",
    scheduledAt: null,
    createdAt: "2026-05-08T08:00:00Z",
    tags: ["payments", "fintech", "banking"],
    metaDescription: "Why real-time payments are changing financial service design.",
  },
  {
    id: "mock-7",
    topic: "Education",
    title: "Personalized Learning With Generative AI: What Actually Works",
    excerpt: "Generative AI can personalize learning when paired with strong assessment loops.",
    body,
    wordCount: 1320,
    readTime: "6 min",
    seoScore: 9.0,
    readabilityScore: 8.9,
    engagementScore: 9.2,
    status: "published",
    publishedAt: "2026-05-07T14:00:00Z",
    scheduledAt: null,
    createdAt: "2026-05-07T11:00:00Z",
    tags: ["education", "learning", "ai"],
    metaDescription: "Evidence-based uses of generative AI in personalized learning.",
  },
  {
    id: "mock-8",
    topic: "Supply Chain",
    title: "Predictive Logistics After the Era of Just-In-Time Fragility",
    excerpt: "Supply chain leaders are pairing resilience planning with predictive systems.",
    body,
    wordCount: 1050,
    readTime: "5 min",
    seoScore: 8.3,
    readabilityScore: 8.1,
    engagementScore: 8.4,
    status: "scheduled",
    publishedAt: null,
    scheduledAt: "2026-05-17T16:00:00Z",
    createdAt: "2026-05-12T16:20:00Z",
    tags: ["logistics", "supply-chain", "forecasting"],
    metaDescription: "How predictive logistics improves supply chain resilience.",
  },
  {
    id: "mock-9",
    topic: "Developer Tools",
    title: "AI Coding Agents and the Future of Software Maintenance",
    excerpt: "Coding agents are becoming useful for tests, migrations, and long-running maintenance.",
    body,
    wordCount: 940,
    readTime: "4 min",
    seoScore: 8.7,
    readabilityScore: 8.3,
    engagementScore: 8.8,
    status: "published",
    publishedAt: "2026-05-06T17:30:00Z",
    scheduledAt: null,
    createdAt: "2026-05-06T14:10:00Z",
    tags: ["software", "agents", "engineering"],
    metaDescription: "The practical software maintenance tasks AI coding agents can handle.",
  },
  {
    id: "mock-10",
    topic: "Space Economy",
    title: "Satellite Data Is Becoming a Mainstream Business Intelligence Layer",
    excerpt: "Satellite data is moving into agriculture, insurance, logistics, and climate analytics.",
    body,
    wordCount: 1015,
    readTime: "5 min",
    seoScore: 7.8,
    readabilityScore: 7.9,
    engagementScore: 8.5,
    status: "draft",
    publishedAt: null,
    scheduledAt: null,
    createdAt: "2026-05-05T10:00:00Z",
    tags: ["space", "data", "analytics"],
    metaDescription: "How satellite data is entering mainstream analytics products.",
  },
  {
    id: "mock-11",
    topic: "Retail",
    title: "The New Personalization Stack for Omnichannel Retail",
    excerpt: "Retailers are unifying commerce data to power more useful personalization.",
    body,
    wordCount: 830,
    readTime: "4 min",
    seoScore: 8.1,
    readabilityScore: 8.5,
    engagementScore: 7.9,
    status: "published",
    publishedAt: "2026-05-04T09:15:00Z",
    scheduledAt: null,
    createdAt: "2026-05-04T08:10:00Z",
    tags: ["retail", "commerce", "personalization"],
    metaDescription: "What modern retail personalization requires across channels.",
  },
];

export const mockActivityFeed: ActivityItem[] = [
  { id: 1, agent: "Research Agent", action: "Searched: 'perovskite solar cells 2026'", time: "2 min ago", status: "complete" },
  { id: 2, agent: "Writer Agent", action: "Generated 1,124 word article", time: "4 min ago", status: "complete" },
  { id: 3, agent: "Editor Agent", action: "Quality score: 8.9/10 approved", time: "5 min ago", status: "complete" },
  { id: 4, agent: "Scheduler Agent", action: "Scheduled for 09:00 AM", time: "6 min ago", status: "complete" },
  { id: 5, agent: "Research Agent", action: "Scraped 5 sources on climate tech", time: "12 min ago", status: "complete" },
  { id: 6, agent: "Editor Agent", action: "SEO pass added meta description", time: "18 min ago", status: "complete" },
  { id: 7, agent: "Writer Agent", action: "Drafted outline for AI operations", time: "23 min ago", status: "complete" },
  { id: 8, agent: "Scheduler Agent", action: "Queued publish task in Celery", time: "31 min ago", status: "complete" },
  { id: 9, agent: "Research Agent", action: "Generated 3 targeted queries", time: "42 min ago", status: "complete" },
  { id: 10, agent: "Editor Agent", action: "Requested one rewrite loop", time: "1 hr ago", status: "running" },
];

export const mockChartData: ChartPoint[] = Array.from({ length: 30 }, (_, index) => {
  const articles = ((index * 7) % 4) + 1;
  return {
    date: new Date(Date.now() - (29 - index) * 86400000).toLocaleDateString("en", {
      month: "short",
      day: "numeric",
    }),
    articles,
    cumulative: 0,
  };
}).reduce<ChartPoint[]>((acc, item) => {
  const previous = acc[acc.length - 1]?.cumulative || 0;
  acc.push({ ...item, cumulative: previous + item.articles });
  return acc;
}, []);

export const mockRuns: PipelineRunRecord[] = [
  {
    id: "run-1",
    topic: "Renewable energy storage",
    status: "completed",
    agentsCompleted: 4,
    duration: "72s",
    articlesCreated: 1,
    date: "2026-05-14T09:00:00Z",
    state: { step_history: ["research", "writer", "editor", "scheduler"] },
  },
  {
    id: "run-2",
    topic: "AI coding agents",
    status: "completed",
    agentsCompleted: 4,
    duration: "65s",
    articlesCreated: 1,
    date: "2026-05-13T13:00:00Z",
    state: { publish_status: "scheduled", scores: { seo: 8.7 } },
  },
  {
    id: "run-3",
    topic: "Carbon capture economics",
    status: "reviewed",
    agentsCompleted: 3,
    duration: "81s",
    articlesCreated: 1,
    date: "2026-05-12T16:00:00Z",
    state: { rewrite_loops: 1, publish_status: "scheduled" },
  },
];

const minute = 60 * 1000;
const now = Date.now();

function isoAgo(minutes: number): string {
  return new Date(now - minutes * minute).toISOString();
}

export const mockPipelineTimelineRuns: PipelineTimelineRun[] = [
  {
    id: "timeline-run-1",
    topic: "AI regulation and enterprise compliance",
    status: "running",
    startedAt: isoAgo(18),
    endedAt: null,
    totalDurationMs: 18 * minute,
    agentResults: [
      {
        agentName: "Research Agent",
        status: "success",
        durationMs: 18400,
        tokensUsed: 3120,
        outputText: "Collected policy updates from the EU AI Act, US executive guidance, and enterprise governance sources.",
      },
      {
        agentName: "Writer Agent",
        status: "running",
        durationMs: 9400,
        tokensUsed: 1980,
        outputText: "Drafting an operational risk framework for AI compliance teams.",
      },
      { agentName: "Editor Agent", status: "running", durationMs: 0, tokensUsed: 0 },
      { agentName: "Scheduler Agent", status: "running", durationMs: 0, tokensUsed: 0 },
    ],
  },
  {
    id: "timeline-run-2",
    topic: "Renewable energy storage breakthroughs",
    status: "success",
    startedAt: isoAgo(132),
    endedAt: isoAgo(130),
    totalDurationMs: 126000,
    articleRoute: "/content/mock-1",
    agentResults: [
      { agentName: "Research Agent", status: "success", durationMs: 31200, tokensUsed: 4200, outputText: "Synthesized battery, grid storage, and thermal storage research." },
      { agentName: "Writer Agent", status: "success", durationMs: 43800, tokensUsed: 6900, outputText: "Generated a 1,140 word article with five sections." },
      { agentName: "Editor Agent", status: "success", durationMs: 27400, tokensUsed: 3100, outputText: "Readability 8.8, SEO 9.1, engagement 8.6." },
      { agentName: "Scheduler Agent", status: "success", durationMs: 23600, tokensUsed: 720, outputText: "Queued publication for the next available content slot." },
    ],
  },
  {
    id: "timeline-run-3",
    topic: "Blockchain finance risk controls",
    status: "success",
    startedAt: isoAgo(390),
    endedAt: isoAgo(388),
    totalDurationMs: 103000,
    articleRoute: "/content/mock-6",
    agentResults: [
      { agentName: "Research Agent", status: "success", durationMs: 24400, tokensUsed: 3600, outputText: "Reviewed stablecoin, custody, AML, and settlement infrastructure sources." },
      { agentName: "Writer Agent", status: "success", durationMs: 35100, tokensUsed: 5420, outputText: "Drafted a practical explainer for fintech operators." },
      { agentName: "Editor Agent", status: "success", durationMs: 26500, tokensUsed: 2840, outputText: "Balanced compliance tone and tightened section flow." },
      { agentName: "Scheduler Agent", status: "success", durationMs: 17000, tokensUsed: 640, outputText: "Saved and scheduled article successfully." },
    ],
  },
  {
    id: "timeline-run-4",
    topic: "Healthcare AI documentation workflows",
    status: "success",
    startedAt: isoAgo(1560),
    endedAt: isoAgo(1558),
    totalDurationMs: 118000,
    articleRoute: "/content/mock-5",
    agentResults: [
      { agentName: "Research Agent", status: "success", durationMs: 29800, tokensUsed: 4050, outputText: "Gathered clinical documentation, privacy, and workflow adoption notes." },
      { agentName: "Writer Agent", status: "success", durationMs: 40900, tokensUsed: 6110, outputText: "Created an article focused on clinical operations leaders." },
      { agentName: "Editor Agent", status: "success", durationMs: 30500, tokensUsed: 3180, outputText: "Generated meta description and improved compliance wording." },
      { agentName: "Scheduler Agent", status: "success", durationMs: 16800, tokensUsed: 610, outputText: "Scheduled article for weekday publishing window." },
    ],
  },
  {
    id: "timeline-run-5",
    topic: "Cybersecurity automation for small business",
    status: "failed",
    startedAt: isoAgo(2360),
    endedAt: isoAgo(2358),
    totalDurationMs: 97000,
    errorMessage: "Editor Agent rejected the draft after SEO score 5.4 and engagement score 5.8. Rewrite limit reached before publishing.",
    agentResults: [
      { agentName: "Research Agent", status: "success", durationMs: 22300, tokensUsed: 3180, outputText: "Found sources on phishing, endpoint defense, backups, and managed detection." },
      { agentName: "Writer Agent", status: "success", durationMs: 38100, tokensUsed: 5900, outputText: "Generated initial draft but leaned too generic for the target query." },
      { agentName: "Editor Agent", status: "failed", durationMs: 30100, tokensUsed: 3340, outputText: "SEO score 5.4, readability 7.0, engagement 5.8. Failed quality gate." },
      { agentName: "Scheduler Agent", status: "failed", durationMs: 6500, tokensUsed: 210, outputText: "Publish skipped because edited content did not pass quality threshold." },
    ],
  },
  {
    id: "timeline-run-6",
    topic: "Carbon capture infrastructure economics",
    status: "success",
    startedAt: isoAgo(4370),
    endedAt: isoAgo(4368),
    totalDurationMs: 121000,
    articleRoute: "/content/mock-3",
    agentResults: [
      { agentName: "Research Agent", status: "success", durationMs: 34200, tokensUsed: 4740, outputText: "Compared DAC, point-source capture, pipeline, and credit market data." },
      { agentName: "Writer Agent", status: "success", durationMs: 42000, tokensUsed: 6320, outputText: "Drafted an infrastructure-focused market analysis." },
      { agentName: "Editor Agent", status: "success", durationMs: 28200, tokensUsed: 2990, outputText: "Improved argument order and cited credibility notes." },
      { agentName: "Scheduler Agent", status: "success", durationMs: 16600, tokensUsed: 590, outputText: "Scheduled article successfully." },
    ],
  },
  {
    id: "timeline-run-7",
    topic: "Personalized learning with generative AI",
    status: "success",
    startedAt: isoAgo(6760),
    endedAt: isoAgo(6758),
    totalDurationMs: 134000,
    articleRoute: "/content/mock-7",
    agentResults: [
      { agentName: "Research Agent", status: "success", durationMs: 36800, tokensUsed: 5120, outputText: "Collected learning science, adaptive tutoring, and assessment loop references." },
      { agentName: "Writer Agent", status: "success", durationMs: 47400, tokensUsed: 7130, outputText: "Produced an education leader article with implementation sections." },
      { agentName: "Editor Agent", status: "success", durationMs: 32900, tokensUsed: 3560, outputText: "Quality score 9.0 with improved examples and takeaways." },
      { agentName: "Scheduler Agent", status: "success", durationMs: 16900, tokensUsed: 650, outputText: "Published to scheduled content queue." },
    ],
  },
  {
    id: "timeline-run-8",
    topic: "Predictive logistics after supply chain shocks",
    status: "success",
    startedAt: isoAgo(9690),
    endedAt: isoAgo(9688),
    totalDurationMs: 112000,
    articleRoute: "/content/mock-8",
    agentResults: [
      { agentName: "Research Agent", status: "success", durationMs: 28600, tokensUsed: 3890, outputText: "Mapped risk sensing, forecasting, and inventory optimization trends." },
      { agentName: "Writer Agent", status: "success", durationMs: 40100, tokensUsed: 6010, outputText: "Built an article around resilience planning and predictive operations." },
      { agentName: "Editor Agent", status: "success", durationMs: 28100, tokensUsed: 2920, outputText: "Tightened section headings and generated meta description." },
      { agentName: "Scheduler Agent", status: "success", durationMs: 15200, tokensUsed: 560, outputText: "Queued for publication." },
    ],
  },
];
